load("//qt:qt.bzl", "qt_resource")

package(default_visibility = ["//visibility:public"])

exports_files([
    "jesture.svg",
    "jesture.ico",
    "settings.svg",
    "settings.png",
    "show.svg",
    "show.png",
    "hide.svg",
    "hide.png",
    "add.svg",
    "add.png",
    "add_element.svg",
    "add_element.png",
    "cross.svg",
    "cross.png"
])

qt_resource(
    name = "icons",
    files = {
        "jesture.svg": ":jesture.svg",
        "jesture.ico": ":jesture.ico",
        "settings.svg": ":settings.svg",
        "settings.png": ":settings.png",
        "show.svg": ":show.svg",
        "show.png": ":show.png",
        "hide.svg": ":hide.svg",
        "hide.png": ":hide.png",
        "add.svg": ":add.svg",
        "add.png": ":add.png",
        "add_element.svg": ":add_element.svg",
        "add_element.png": ":add_element.png",
        "cross.svg": ":cross.svg",
        "cross.png": ":cross.png"
    },
    prefix = "/jesture/icons",
)
