load("//qt:qt.bzl", "qt_cc_library")

package(default_visibility = ["//visibility:public"])

qt_cc_library(
    name = "video_capture_session",
    srcs = ["video_capture_session.cc"],
    moc_hdrs = ["video_capture_session.h"],
    deps = [
        "@qt//:qt_multimedia",
    ],
)
