load("@rules_qt//:qt.bzl", "qt_cc_binary")

qt_cc_binary(
    name = "jesture",
    srcs = ["jesture.cc"],
    deps = [
        "@rules_qt//:qt_core",
        "@rules_qt//:qt_widgets",
        "@rules_qt//:qt_gui",
        "@rules_qt//:qt_multimedia",
        "@rules_qt//:qt_multimedia_widgets"
    ]
)