package(default_visibility = ["//visibility:public"])

cc_library(
    name = "resources",
    srcs = ["resources.cc"],
    hdrs = ["resources.h"],
    deps = [
        "//icons",
        "@qt//:qt_gui",
        "@qt//:qt_multimedia",
    ],
)
